version: "3"

volumes:
  db-data:
    driver: local
networks:
  app-network:
    driver: bridge

services:
  app:
    image: virginonline/mediasoft:latest
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
  postgres:
    image: postgres:15-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    environment:
      POSTGRES_DB: "mediasoftdb"
      POSTGRES_USER: "mediasoft"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data