version: '3'
vars:
  IMAGE_NAME: virginonline/mediasoft
  IMAGE_TAG: latest

dotenv: [ '.env.{{.ENV}}' ]
includes:
  #Cross-platform tasks
  os:
    taskfile: task/Taskfile_{{OS}}.yml
tasks:
  build:
    desc: build bootJar
    deps:
      - os:build:clean
    cmd:
      task: os:build
  build:check:
    desc: run tests and spotless linter
    cmd:
      task: os:build:check
  build:test:
    desc: run tests
    cmd:
      task: os:build:test
  build:spotless:
    desc: spotless linter
    cmd:
      task: os:build:spotless
  build:clean:
    cmd:
      task: os:build:clean
  docker:build:
    desc: build docker image
    cmds:
      - docker build -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} .
  docker:push:
    desc: push docker image
    cmds:
      - docker push virginonline/mediasoft
  docker:compose:
    desc: start docker compose
    cmds:
      - docker compose --env-file .env.production up -d
