name: Docker image CI
on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and push image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: virginonline/mediasoft
